local opt = vim.opt
opt.autowrite = true
opt.breakindent = true
opt.clipboard = "unnamedplus"
opt.cmdheight = 1
opt.completeopt = "menu,menuone,noselect"
opt.conceallevel = 2
opt.confirm = false
opt.cursorline = true
opt.expandtab = true
opt.fileencoding = "utf-8"
opt.foldcolumn = "1"
opt.foldenable = true
opt.foldlevel = 99
-- opt.foldlevelstart = 0 -- start w/ folds closed
opt.foldlevelstart = -1
opt.foldclose = ""
opt.formatoptions = "jcroqlnt" -- tcqj
opt.grepformat = "%f:%l:%c:%m"
opt.grepprg = "rg --vimgrep"
opt.guifont = "FiraCode Nerd Font Mono Retina"
opt.hlsearch = true
opt.hidden = true
-- opt.hlsearch = false
opt.ignorecase = false
opt.inccommand = "nosplit"
opt.joinspaces = false
opt.laststatus = 0
-- FIX: flickering and inconsistent behavior when using relative with indentline?
-- opt.statuscolumn = "%l %r %C %s"
opt.statuscolumn = "%s %C %l"
opt.relativenumber = true
opt.signcolumn = "yes"
opt.list = false
opt.mouse = "a"
opt.number = true
opt.pumblend = 10
opt.pumheight = 10
opt.scrollback = 100000
opt.scrolloff = 8
opt.sessionoptions = { "buffers", "curdir", "tabpages", "winsize" }
opt.shiftround = true
opt.shiftwidth = 2
opt.shortmess:append { W = true, I = true, c = true }
opt.showmode = false
opt.showtabline = 2
opt.sidescrolloff = 8
opt.spelllang = { "en" }
opt.smartcase = true
opt.smartindent = true
opt.splitbelow = true
opt.splitright = true
opt.splitkeep = "screen"
opt.tabstop = 2
opt.termguicolors = true
opt.timeoutlen = 242
opt.title = true
opt.undofile = true
opt.undolevels = 100000
opt.updatetime = 20
opt.wildmode = "longest:full,full"
opt.winminwidth = 5
opt.wrap = false
opt.writebackup = false
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.g.markdown_recommended_style = 0
-- vim.keymap.set({ "n", "v" }, "<Space>", "<Nop>", { silent = true })
vim.cmd [[set noswapfile]]
vim.cmd "set sessionoptions+=globals"
vim.cmd "set whichwrap+=<,>,[,],h,l"
vim.cmd [[set iskeyword+=-]]
-- vim.cmd [[
--   set foldmethod=marker
--   let g:chalk_char = "."
--   au BufRead,BufNewFile *.vim let b:chalk_space_before = 1
-- ]]
