#pragma once

#define VIAL_KEYBOARD_UID \
    { 0xB6, 0xBB, 0xD5, 0xAE, 0x4F, 0x37, 0x59, 0xD5 }

#define VIAL_TAP_DANCE_ENTRIES 11
#define DYNAMIC_KEYMAP_MACRO_COUNT 8
#define VIAL_COMBO_ENTRIES 27
#define VIAL_KEY_OVERRIDE_ENTRIES 8
