# MCU name
MCU = atmega32u4
BOOTLOADER = caterina

LTO_ENABLE = yes
QMK_SETTINGS = yes
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
KEYLOCK_ENABLE = no
SPLIT_KEYBOARD = yes
NO_USB_STARTUP_CHECK = yes

ENCODER_ENABLE = no
BLUETOOTH_ENABLE = no
BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
SLEEP_LED_ENABLE = no
JOYSTICK_ENABLE = no
POINTING_DEVICE_ENABLE = no

AUDIO_ENABLE = no
MUSIC_ENABLE = no
EXTRA_KEY_ENABLE = no
MIDI_ENABLE = no


LEADER_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = yes
STENO_ENABLE = no
MOUSEKEY_ENABLE = no

NKRO_ENABLE = yes
IGNORE_MOD_TAP_INTERRUPT = yes
MAGIC_ENABLE = no
AUTO_SHIFT_ENABLE = no
AUTO_SHIFT_MODIFIERS = no
SWAP_HANDS_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no

TERMINAL_ENABLE = no
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
UCIS_ENABLE = no
